name: MLOps CI/CT Pipeline

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  validate-and-train:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Set up DVC
        uses: iterative/setup-dvc@v1

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r backend/requirements.txt

      # --- NEW: Authenticate with Google Drive and Pull Data ---
      - name: Authenticate DVC with Google Drive
        env:
          GDRIVE_CREDENTIALS_DATA: ${{ secrets.GDRIVE_CREDENTIALS_DATA }}
        run: |
          # This command securely creates the credentials file from the GitHub Secret
          echo "$GDRIVE_CREDENTIALS_DATA" > gdrive-credentials.json
          
          # Configure DVC to use the credentials file
          dvc remote modify myremote gdrive_service_account_json_file_path gdrive-credentials.json

      - name: Pull Data from DVC Remote
        run: dvc pull -r myremote

      - name: List Files to Verify Data
        run: ls -R # This helps confirm the data was downloaded

      - name: Run Automated Tests
        run: |
          cd backend
          pytest

      - name: Start MLflow Tracking Server
        run: |
          cd backend
          mlflow server --host 127.0.0.1 --port 5000 --backend-store-uri file:./mlruns &
          sleep 5

      - name: Train Fundus Model
        env:
          MLFLOW_TRACKING_URI: http://127.0.0.1:5000
        run: python backend/model_training.py --type fundus

      - name: Train OCT Model
        env:
          MLFLOW_TRACKING_URI: http://127.0.0.1:5000
        run: python backend/model_training.py --type oct
